---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: minio.yaml
      sourceRef:
        kind: HelmRepository
        name: https://charts.bitnami.com/bitnami
        namespace: ${releaseNamespace}
      version: 2022.11.26
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: keycloak
  targetNamespace: ${releaseNamespace}
