---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: nexus.yaml
      sourceRef:
        kind: HelmRepository
        name: https://SonarSource.github.io/helm-chart-sonarqube
        namespace: ${releaseNamespace}
      version: 1.1.1 .  # Version that appears in UI
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: keycloak
  targetNamespace: ${releaseNamespace}
