---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: tempo.yaml
      sourceRef:
        kind: HelmRepository
        name: https://grafana.github.io/helm-charts
        namespace: ${releaseNamespace}
      version: 20.0.9
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: keycloak
  targetNamespace: ${releaseNamespace}
