---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nexus
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: nexus.yaml
      sourceRef:
        kind: HelmRepository
        name: https://sonatype.github.io/helm3-charts/
        namespace: ${releaseNamespace}
      version: 20.0.9
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: nexus
  targetNamespace: ${releaseNamespace}
